### ISSUE TITLE
Outdated version on Rubygems

### ISSUE THREAD

**Issue by jonathansimmons** [wmlele/devise-otp#15]
When running the install generator from a fresh bundle this morning my `devise.rb` had 

``` ruby
config.recover_tokens
```

instead of 

``` ruby
config.otp_recovery_tokens = 10
```

it looks right in repo, it looks like rubygems needs a version bump from `0.2.3` to `0.2.4`?

**Comment by jonathansimmons** [comment]
The outdated version also has changes in the generated migration. Update the title to reflect the real issue.

**Comment by dannycodes** [comment]
There is now devise-otp-rails5 gem

**Comment by strzibny** [comment]
@dannycodes it's my gem and I just became a co-maintainer last week. I will fix this gem and do a fresh release for Rails 7.

**Comment by strzibny** [comment]
I released 0.3.0 yesterday, so closing.
