### ISSUE TITLE
Workflow changes

### ISSUE THREAD

**Issue by jonathansimmons** [wmlele/devise-otp#24]
In using this gem I've made some workflow changes that I think are critical to the core of this gem. I'm going to list them out here, with my reasons for the change. @wmlele if you would provide your feedback on each so I can determine which are worth taking the time to make a pull request for. 

#### Problem
To me it's odd that I can enable the otp flag in the db without confirming a token. What this means is that if I just visit `/users/otp/token` and choose enable then sign out. I'm locked out of my account. 

#### My Fix
What I do is modify the views so that the user is displayed an token field and must submit a valid TOTP token to activate otp. Example

<img width="1258" alt="screen shot 2015-07-28 at 1 01 25 pm" src="https://cloud.githubusercontent.com/assets/945202/8939231/cc52ab96-3528-11e5-8015-99d315e79a9f.png">

==============

#### Problem
Requiring a token on credential refresh just feels cumbersome. I remove this code in every case that I've use it. Modeling more after github which only requires that you re-enter your password 

#### My Fix
Just remove the necessity for a TOTP token during credential refresh. 

==============

#### Problem
Right now you can only trust a browser once signed in. If I miss that though it would be nice to be provided with the option to trust the browser as I sign in. 

#### My Fix
Add a "Trust this browser" checkbox to the token form during signup. Example 

<img width="572" alt="screen shot 2015-07-28 at 1 09 50 pm" src="https://cloud.githubusercontent.com/assets/945202/8939429/f91598c2-3529-11e5-9b4c-553def4ada1f.png">

==============

#### Problem
If a user in my app contact me because they can't access their account and don't have an recovery token, at the moment I can only take them at their word and unlock their account. 

#### Proposed Fix Options
- We could request a backup email during activation which would be used for an application administrator to send a token to.
- We could implement the twilio gem to allow the user to provide a sms number to receive a backup token. 

==============

@wmlele I have codes solutions for some of these already. Just wanted to get your thoughts before I open a PR that you're not interested in.

**Comment by wmlele** [comment]
Thumbs up for the first 3 changes. First and number 3 were on my list, so, contributions on all three of them are more than welcome. And thanks in advance.

I am perplexed on the fourth issue. I kind of feel both solutions, and in general, the process of collecting user data for id purpose, don't belong to the otp gem. Of course I do agree some sort of identification backup is needed in the full application, but maybe it's better to leave what data is collected and how to the implementor. 
I guess I would go for the SMS way, but that doesn't even need to be OTP based, just a random secret.

**Comment by jonathansimmons** [comment]
Yea, I sort agree about the fourth being best suited to let the implementor sort out. I'll try to get PR's on the other 3 submitted in the next couple days.

**Comment by wmlele** [comment]
Danke Schön!

**Comment by shimms** [comment]
Hi @jonathansimmons - did you end up doing any code changes for Problem 1 (quickly checked out your branches but none jumped out at me as being obviously this)? 

Before heading down the path of building the same change, wanted to see if you'd done it already.

This is something I'm very keen on seeing implemented as well.

**Comment by jonathansimmons** [comment]
@shimms no I didn't. I have my own implementation in a couple apps but each is different based on that apps needs. 

That is ultimately exactly why I didn't create something for the gem. I think ever app is going to have different needs. While I don't like the way the gem set it up by default I can't nock that all the necessary info is there for you to build it out on your own. 

Sorry I can be of more help.

**Comment by jonathansimmons** [comment]
Closing this as there is no actionable issue here. 

The first change I never PR'ed because As stated above it feels like that should be handled on a per implementation basis. 

 #26 resolves the second proposed change.

The third I didn't find time for and the fourth just no longer feels relevant and should be dealt with on a per implementation basis.
