### ISSUE TITLE
unknown attribute 'otp_time_drift' for User in version on Rubygems

### ISSUE THREAD

**Issue by AnthonySuper** [wmlele/devise-otp#29]
It appears you removed the attribute `otp_time_drift` in 7dc5f4dc3639c2e1897b288209ff141fb78b649b, which was a while back. However, trying to disable 2-factor authentication tries to set this attribute, causing an error. 

This is fixed in the current gem version, however the version on Rubygems has broken behavior. Maybe consider pushing 0.2.4 up?

**Comment by jonathansimmons** [comment]
This is a dup of #15, with a touch more info but further emphasizes this should be resolved.

**Comment by strzibny** [comment]
Closing as stale & old. There will be a new version soon.
