### ISSUE TITLE
It looks like Ruby Gems has an outdated/not working version

### ISSUE THREAD

**Issue by common-nighthawk** [wmlele/devise-otp#30]
The gem available through Ruby Gems does not work with the instructions on the README.  Specifically, there is no javascript file on the version on Ruby Gems--so `//= require devise-otp` raises an exception.

I included `gem 'devise-otp', git: 'git://github.com/wmlele/devise-otp.git'` in my Gemfile.

Either update the README or update the gem on Ruby Gems?

**Comment by jonathansimmons** [comment]
Another dup of #15

**Comment by strzibny** [comment]
I just became a co-maintainer last week. I will fix this gem and do a fresh release for Rails 7. Closing as a duplicate issue.
