### ISSUE TITLE
How to plugin into core rotp lib constructor? How to keep block once verified otp? 

### ISSUE THREAD

**Issue by nazarhussain** [wmlele/devise-otp#31]
Hello, 

One thing I need to ask, does `otp_drift_window` is same as duration https://github.com/mdp/rotp/blob/master/lib/rotp/totp.rb#L10 and if I need to set it to less than 1 minute how can do it? 

Other question is I need to block an otp if once verified. So it must not came back again with in that drift window. Is there any hook available from which I can build my own logic of verification?

**Comment by strzibny** [comment]
You might be able to do something with some monkey patching. Anyway I am closing this as stale & old.
