### ISSUE TITLE
Installation With Existing Users

### ISSUE THREAD

**Issue by lminhthien-tma** [wmlele/devise-otp#40]
```
MODEL.where(:otp_auth_secret => nil).find_each do |user|
  user.send(:generate_otp_auth_secret)
  user.send(:generate_otp_persistence_seed)
  user.save!
end
```

Here is my way to install with existing users to prevent the error that is QR code is invalid when Google Authenticator use to read.
Are there another ways to setup with existing users?

**Comment by strzibny** [comment]
I think `user#enable_otp!` should be used if you want to enable OTP.
