### ISSUE TITLE
How to migrate from devise_google_authenticator ?

### ISSUE THREAD

**Issue by zedtux** [wmlele/devise-otp#58]
We are currently maintaining a fork of the `devise_google_authenticator`, but that fork is not in a very good shape and after finding this `devise-otp` gem, we would like to migrate but we don't want to miss anything so we were looking for a migration documentation but we couldn't find one.

Could you please describe the migration process in order to migrate from the `devise_google_authenticator` gem to this `devise-otp` gem ?

**Comment by strzibny** [comment]
Hello, unfortunately I never used `devise_google_authenticator` so I don't know the differences. I see they use the `rotp` gem too so I believe the migration should be possible.

**Comment by strzibny** [comment]
I'll close this issue for now, let me know if you have some more questions.

**Comment by zedtux** [comment]
That doesn't help, but I guess we will never do it since you can't help and we're not looking for it for months. Thank you anyway.
