### ISSUE TITLE
Issue with multiple models using otp strategy

### ISSUE THREAD

**Issue by paweld-iRonin** [wmlele/devise-otp#86]
Hello 👋 

I ran into an issue with the setup, where I had two models using the strategy. The first one is `User` and the second one is `Admin`. When I'm using `Admin`, after setting up the QR code I'm redirected to the path for `User` - the redirection is initiated here: https://github.com/wmlele/devise-otp/blob/master/app/controllers/devise_otp/devise/otp_tokens_controller.rb#L36 - I think this issue exists because the redirection is not scoped for the current resource. Can we fix it quickly or it's more complex change?

**Comment by strouptl** [comment]
Hi @paweld-iRonin, thanks for the heads up! The scope should be set automatically by the devise controller, but there could be a route conflict, or something else going on that I am not aware of.

Is there any way you could post a copy of your routes file? I will see what I can do from my side, as well.

**Comment by strouptl** [comment]
OK, I see what is going on - my admin and user routes are just separated by subdomain, so there is no conflict in my application. Let me see what I can do.

**Comment by paweld-iRonin** [comment]
@strouptl thank you!

**Comment by paweld-iRonin** [comment]
Hello @strouptl any news on this?

**Comment by strouptl** [comment]
Hi @paweld-iRonin, thank you for your patience. I have a simple fix ready for you, and am submitting a PR now.

**Comment by paweld-iRonin** [comment]
@strouptl I really appreciate your help, thank you

**Comment by strouptl** [comment]
My pleasure! Thanks for bringing it to our attention.
