### ISSUE TITLE
Incorrect error message when entering valid token after entering invalid token

### ISSUE THREAD

**Issue by pkarjala** [wmlele/devise-otp#94]
devise 4.9.4
devise-otp 0.7.1

Steps to reproduce:

1. Log into site using username/password.
2. Enter incorrect token value and press "Submit Token".
3. Receive an error message `The token you provided was invalid.` and be redirected back to token entry page.
4. Enter a valid token value and press "Submit Token".
5. Be successfully logged in, but still get error message `The token you provided was invalid.`

This occurs each time after entering an invalid token, then subsequently entering a valid token.  Once you have logged into the application, the error message displays.  Navigating to another page in the application without logging out causes the error message to disappear, so it is only happening after the initial failed and subsequent successful token login.

**Comment by strzibny** [comment]
Could you try to track this down and submit a PR?

**Comment by pkarjala** [comment]
I will try to find some time to do so!

**Comment by pkarjala** [comment]
OK, I tracked this down to https://github.com/wmlele/devise-otp/blob/33b3b7752b2a5cb8d9490747abb5818ff6687a69/lib/devise_otp_authenticatable/controllers/helpers.rb#L19

The issue may be that the messages are being set using `flash` instead of `flash.now`.  When `flash` is used by itself, the messages will persist through redirects.  For `flash.now` they will only show for the currently loaded page.

See https://api.rubyonrails.org/classes/ActionDispatch/Flash/FlashHash.html#method-i-now, https://stackoverflow.com/questions/18748072/rails-4-flash-message-persists-for-the-next-page-view, and https://medium.com/@tdonovan79/flash-in-rails-apps-df5ef389139f for additional info.

I'm not sure if there needs to be differentiation between some flash messages persisting through redirects and others only for the current page.  So I haven't created a PR yet as there is probably some nuance there that may be affected by creating all messages with `flash.new`.

**Comment by pkarjala** [comment]
Can confirm that this does impact other places by altering the above call to `flash`, resulting in messages not showing up when they should be.  So there needs to be some further nuance on when to call `flash` and when to call `flash.now` for alerts and messages.

**Comment by strzibny** [comment]
Thanks for the investigation, I agree

**Comment by strouptl** [comment]
FYI, I found a couple of additional occurrences of the flash message issue. See PR #96 for resolution.

**Comment by strzibny** [comment]
Okay, I think we can close this and I'll likely release 1.0 soon.
